### ISSUE TITLE
Laravel 5.5 support？

### ISSUE THREAD

**Issue by summerblue** [freshbitsweb/laravel-log-enhancer#1]
5.5 is the latest LTS, should be supported.

**Comment by gauravmak** [comment]
Laravel's logging system had major improvements with [version 5.6](https://laravel.com/docs/5.6/releases#laravel-5.6) and this package is using new functionality for log enhancements.

For version 5.5, our other package [Slack error notifier](https://github.com/freshbitsweb/slack-error-notifier) can be used which offers the similar functionality for Slack notifications.

Though it doesn't offer enhancements to log files currently, we would happily accept a pull request for the same.
