### ISSUE TITLE
Class session does not exist

### ISSUE THREAD

**Issue by apair** [freshbitsweb/laravel-log-enhancer#12]
Hi,
When I upgrade Laravel to 5.7 from 5.6, I got this : 
```
Class session does not exist

```
and It thrown by `RequestDataProcessor` class, when want to access session() helper.
my solution was disable `log_session_data` in config file, run the application, enable it again.

**Comment by repat** [comment]
I had the same problem and the same solution also helped me.

**Comment by gauravmak** [comment]
@apair Thanks for pointing this out. We will check that.

**Comment by gauravmak** [comment]
@apair Sorry for the late update.

I can't think of any solution here. And not sure why it doesn't work after the upgrade and starts working after a request or two.

Please let me know if the issue persists with newer upgrades. Thanks.
