### ISSUE TITLE
Lumen compatibility

### ISSUE THREAD

**Issue by josegus** [freshbitsweb/laravel-log-enhancer#15]
This is not an issue, is more a request for asking if this package could be compatible with Lumen. 

I've used this package in a couple of Laravel projects, works great, but in lumen we cannot access to request() helper.

![image](https://user-images.githubusercontent.com/13947849/65995653-f41dce00-e463-11e9-8b06-ff38957b5642.png)

**Comment by gauravmak** [comment]
@josegus We don't generally use Lumen in any of our projects so I am not sure if this package would work properly there.

If you can test and confirm, I am open to a PR for the same.
