### ISSUE TITLE
Does this work on Lumen?

### ISSUE THREAD

**Issue by judgej** [freshbitsweb/laravel-log-enhancer#16]
It would be great if if works on Lumen - fantastic in fact. If some additional steps are needed (for example, loading the provider), they should be documented. If it is not supported at all, then that should probably also be documented also.

Let me know if I can help.

**Comment by gauravmak** [comment]
Hi Jason,

Seems like there are [some folks](https://github.com/freshbitsweb/laravel-log-enhancer/issues/15) who are willing to use this package with Lumen.

We do not use Lumen so I am not really sure whether this can be easily integrated with it. This package is really simple. [This file](https://github.com/freshbitsweb/laravel-log-enhancer/blob/master/src/RequestDataProcessor.php) is the only important one I think.

You can surely help here. Maybe you can test once and then, we can make the necessary changes together.

Let me know your thoughts.

**Comment by gauravmak** [comment]
Note added in Readme, thanks.

**Comment by judgej** [comment]
Lumen is the main target for this package. We have a number of lumen apps running in containers, and this helps us to pull the logs together from any number of containers.

**Comment by judgej** [comment]
Just added and deleted a comment - was commenting on the wrong repository - just ignore it. Sorry!
