### ISSUE TITLE
Is it possible to add support for Laravel 5.5 LTS?

### ISSUE THREAD

**Issue by JuanDMeGon** [freshbitsweb/laravel-log-enhancer#2]
Hello!
I am just wondering if it is possible to provide support for Laravel 5.5 as it is an LTS version.
Maybe it is just a matter of change the composer.json requirements, but maybe there is an internal dependency on the code.

Thanks :)

**Comment by gauravmak** [comment]
Hey @JuanDMeGon 

As I mentioned in #1 ,  Logging system of the framework had major improvements in 5.6 and this package uses the new feature.

For version 5.5, our other package [Slack error notifier](https://github.com/freshbitsweb/slack-error-notifier) can be used which offers the similar functionality for Slack notifications.
